# ATALHOS VSCODE

# DESCOMENTAR/COMENTAR CODIGO:
# CTRL + K + C = PARA COMENTAR
# CTRL + K + U = PARA DESCOMENTAR
# SHIFT + ALT + A = PARA COMENTAR E DESCOMENTAR UM BLOCO INTEIRO

# COPIAR CODIGO DE LINHA
# SHIFT + ALT + SETA PARA BAIXO = COPIAR O CODIGO SELECIONADO PARA LINHA DA BAIXO

# MOVIMENTAR LINHA DE CODIGO PARA CIMA OU PARA BAIXO
# ALT + SETA PARA CIMA OU PARA BAIXO

# ESCONDER BARRA LATERAL
# CTRL + B

# ESCONDER O TERMINAL
# CTRL + ' (ACENTO GRAVE)

# LOCALIZAR UM CODIGO
# CTRL + F = ABRE UMA FERRAMENTA DE LOCALIZAÇÃO

# SUBSTITUIR CODIGO
# CTRL + F -> DIGITA O CODIGO QUE QUER LOCALIZAR PARA SUBSTITUIR
# CTRL + H -> DIGITA A INFORMAÇÃO QUE DESEJA COLOCAR

# NAVEGAR ENTRE ARQUIVOS
# CTRL + P

# TER DOIS ARQUIVOS ABERTOS
# CTRL + P -> ESCOLHE O ARQUIVO DESEJADO
# CTRL + ENTER -> PARA ABRIR UM AO LADO DO OUTRO

# NAVEGAR NOS DOIS ARQUIVOS ABERTO
# CTRL + 1
# CTRL + 2

# FECHAR ARQUIVO ATUAL
# CTRL + W


# ABRIR CODIGO FONTE
# F12


# VERIFICAR O CODIGO LINHA POR LINHA PARA DESCOBRIR ERROS
# F9 SELECIONA AS LINHAS
# F10 PULA LINHA POR LINHA
# F11 ENTRA DENTRO DA FUNÇÃO DO CODIGO PARA VERIFICAR O CODIGO
# OBS: CASO PASSE A LINHA COM F10 E APRESENTE ERRO, O ERRO SERA A PRIMEIRA LINHA, COPIAR E COLAR NO GOOGLE PARA VERIFICAR DICAS SOBRE O ERRO
# SHIFT + F5 PARA A FUNÇÃO LINHA POR LINHA
# CONSOLE DE DEPURAÇÃO - VERIFICA EM TEMPO REAL OS VALORES DO CODIGO
